//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandlockProfile) DeepCopyInto(out *LandlockProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandlockProfile.
func (in *LandlockProfile) DeepCopy() *LandlockProfile {
	if in == nil {
		return nil
	}
	out := new(LandlockProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandlockProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandlockProfileList) DeepCopyInto(out *LandlockProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LandlockProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandlockProfileList.
func (in *LandlockProfileList) DeepCopy() *LandlockProfileList {
	if in == nil {
		return nil
	}
	out := new(LandlockProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandlockProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandlockProfileSpec) DeepCopyInto(out *LandlockProfileSpec) {
	*out = *in
	if in.ProfilesByContainer != nil {
		in, out := &in.ProfilesByContainer, &out.ProfilesByContainer
		*out = make(map[string]ProfileByBinary, len(*in))
		for key, val := range *in {
			var outVal map[string]Profile
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(ProfileByBinary, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandlockProfileSpec.
func (in *LandlockProfileSpec) DeepCopy() *LandlockProfileSpec {
	if in == nil {
		return nil
	}
	out := new(LandlockProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandlockProfileStatus) DeepCopyInto(out *LandlockProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandlockProfileStatus.
func (in *LandlockProfileStatus) DeepCopy() *LandlockProfileStatus {
	if in == nil {
		return nil
	}
	out := new(LandlockProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Profile) DeepCopyInto(out *Profile) {
	*out = *in
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadWrite != nil {
		in, out := &in.ReadWrite, &out.ReadWrite
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadExec != nil {
		in, out := &in.ReadExec, &out.ReadExec
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadWriteExec != nil {
		in, out := &in.ReadWriteExec, &out.ReadWriteExec
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Profile.
func (in *Profile) DeepCopy() *Profile {
	if in == nil {
		return nil
	}
	out := new(Profile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ProfileByBinary) DeepCopyInto(out *ProfileByBinary) {
	{
		in := &in
		*out = make(ProfileByBinary, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileByBinary.
func (in ProfileByBinary) DeepCopy() ProfileByBinary {
	if in == nil {
		return nil
	}
	out := new(ProfileByBinary)
	in.DeepCopyInto(out)
	return *out
}
