name: Publish Docs using Antora

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "antora-playbook.yml"
      - ".github/workflows/antora-build.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Install Dependencies
        run: npm ci

      - name: Generate Site
        run: npx antora antora-playbook.yml

      - name: Configure Git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Clone existing gh-pages branch and commit
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages-worktree gh-pages
          cp -r ./build/site/* gh-pages-worktree/
          # Disable Jekyll
          touch gh-pages-worktree/.nojekyll

          cd gh-pages-worktree
          git add .
          git commit -m "Update GitHub Pages content" || echo "No changes to commit"
          git push origin gh-pages
