name: CI

on:
  workflow_call:
  push:
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - run: make test
      - name: Upload unit-tests coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          name: unit-tests
          directory: coverage
          flags: unit-tests
          verbose: true
          token: ${{ secrets.CODECOV_REPO_TOKEN }}

  helm-unittest:
    name: Helm unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      # Disable plugin verification until the following issue is addressed https://github.com/helm-unittest/helm-unittest/issues/777
      - name: Install Helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false
      - run: make helm-unittest

  golangci:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - run: make lint

  commitlint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Discover latest version of commitlint
        id: discover-commitlint-version
        run: |
          latest_version=$(curl -s https://api.github.com/repos/conventional-changelog/commitlint/releases/latest | jq -r '.tag_name')
          echo "version=$latest_version" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache commitlint
        id: cache-commitlint
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            node_modules
            package.json
            package-lock.json
          key: ${{ runner.os }}-commitlint-${{ steps.discover-commitlint-version.outputs.version }}
      - name: Install commitlint
        if: steps.cache-commitlint.outputs.cache-hit != 'true'
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
